[package]
name = "variables"
version = "2.3.4"
authors = ["moriya <moriya0114.pharmacy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
